[package]
name = "node_modules_size"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
walkdir = "2.3"
chrono = "0.4"
